[project]
name = "AfriTeVa"
version = "0.1.0"
description = "LLMs for African Languages"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "datasets>=3.1.0",
    "nltk>=3.9.1",
    "python-dotenv>=1.0.1",
    "sentencepiece>=0.2.0",
]

[dependency-groups]
torch = [
    "accelerate>=1.3.0",
    "evaluate>=0.4.3",
    "scikit-learn>=1.6.1",
    "torch>=2.5.1",
    "transformers>=4.46.3",
    "wandb>=0.19.4",
]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "nvitop>=1.4.1",
]
t5x = [
    # "orbax-checkpoint==0.5.15",
    "pycountry>=24.6.1",
    "t5>=0.9.4",
    "tensorflow-io>=0.37.1",
]
t5x-gpu = [
    "jax[cuda12-pip]>=0.4.38",
]
t5x-tpu = [
]

[project.scripts]
teva_torch = "teva.torch_module.cli:main"

[tool.uv]
package = true
conflicts = [
    [
      { group = "t5x-gpu" },
      { group = "t5x-tpu" },
    ],
]

[tool.uv.sources]
jax_gpu = { index = "jax-gpu", marker = "sys_platform == 'linux' and extra == 'gpu'" }
jax_tpu = { index = "jax-tpu", marker = "sys_platform == 'linux' and extra == 'tpu'" }
torch = { index = "pytorch", marker = "sys_platform == 'linux'" }

[[tool.uv.index]]
name = "pytorch"
url = 'https://download.pytorch.org/whl/cu121'
explicit = true

[[tool.uv.index]]
name = "jax-tpu"
url = "https://storage.googleapis.com/jax-releases/libtpu_releases.html"
explicit = true

[[tool.uv.index]]
name = "jax-gpu"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
explicit = true
